In [235]:
import pandas as pd
from unidecode import unidecode
import matplotlib.pyplot as plt
import seaborn as sns
import json

import plotly.express as px
import psycopg2 as pg
from datetime import datetime, timedelta


import requests

from pygal.style import Style
import geopandas as gpd

Esta parte

In [237]:
########################### CONEXAO TABELA IMUNIZAÇÃO ###########################

conexao = pg.connect(database = "*****",
                           host="*****",
                           user="*****",
                           password="*****",
                           port="****")


cursor = conexao.cursor()
query = "SELECT * FROM imunizacao.imunizacao_bivalente"

cursor.execute(query)
resultados = cursor.fetchall()

data = pd.DataFrame(resultados, columns=[desc[0] for desc in cursor.description])

In [238]:
data

,dat_carga,paciente_cpf,paciente_endereco_nm_municipio,paciente_idade,paciente_cns,estabelecimento_municipio_nome,vacina_data_aplicacao,vacina_lote,vacina_grupo_atendimento_nome,categoria,...,faixa_etaria_2,pop,nu_latitude,nu_longitude,total,macrorregiao_saude,regiao_saude,cod_ibge_7,uf,municipio
0,2024-06-30,15937330978,RIO DO OESTE,86,708602050709182,RIO DO OESTE,2023-03-06,GF9670,FAIXA ETARIA,FAIXA ETARIA,...,qt_80_ou_mais,153.0,-27.193396,-49.796999,7747,VALE DO ITAJAI,ALTO VALE DO ITAJAÍ,4214607,SC,RIO DO OESTE
1,2024-06-30,18207308915,NAVEGANTES,69,700505926316758,ITAJAI,2023-03-06,GF9670,PESSOAS DE 65 A 69 ANOS,FAIXA ETARIA,...,qt_65_69,1622.0,-26.899395,-48.655280,86401,FOZ DO RIO ITAJAI,FOZ DO RIO ITAJAÍ,4211306,SC,NAVEGANTES
2,2024-06-30,28001257053,PASSO DE TORRES,63,707000814406434,PASSO DE TORRES,2023-03-06,GJ5106,FAIXA ETARIA,FAIXA ETARIA,...,qt_60_64,400.0,-29.323230,-49.722518,12897,SUL,EXTREMO SUL CATARINENSE,4212254,SC,PASSO DE TORRES
3,2024-06-30,41984749900,JOINVILLE,61,708307221012560,JOINVILLE,2023-03-06,GF9670,PESSOAS DE 18 A 64 ANOS,FAIXA ETARIA,...,qt_60_64,15383.0,-26.305088,-48.846093,616317,NORTE E NORDESTE,NORDESTE,4209102,SC,JOINVILLE
4,2024-06-30,42019133920,JOINVILLE,75,705701442301030,JOINVILLE,2023-03-06,GF9670,PESSOAS DE 75 A 79 ANOS,FAIXA ETARIA,...,qt_75_79,5461.0,-26.305088,-48.846093,616317,NORTE E NORDESTE,NORDESTE,4209102,SC,JOINVILLE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
852358,2024-06-30,90916719987,FLORIANOPOLIS,52,703107604179590,BIGUACU,2023-06-14,2F3006A,FAIXA ETARIA,FAIXA ETARIA,...,qt_50_54,17334.0,-27.596904,-48.549454,537211,GRANDE FLORIANOPOLIS,GRANDE FLORIANÓPOLIS,4205407,SC,FLORIANÓPOLIS
852359,2024-06-30,44975732904,BLUMENAU,61,700501512216151,BLUMENAU,2023-04-20,GF9670,FAIXA ETARIA,FAIXA ETARIA,...,qt_60_64,9703.0,-26.918752,-49.066025,361261,VALE DO ITAJAI,MÉDIO VALE DO ITAJAÍ,4202404,SC,BLUMENAU
852360,2024-06-30,56156413049,PALHOCA,54,700406979498348,PALHOCA,2023-06-29,GJ9239,FAIXA ETARIA,FAIXA ETARIA,...,qt_50_54,6331.0,-27.642670,-48.669511,222598,GRANDE FLORIANOPOLIS,GRANDE FLORIANÓPOLIS,4211900,SC,PALHOÇA
852361,2024-06-30,14601737087,ITAPIRANGA,85,700604487048167,ITAPIRANGA,2023-03-03,GJ5106,FAIXA ETARIA,FAIXA ETARIA,...,qt_80_ou_mais,227.0,-27.171014,-53.709862,16638,GRANDE OESTE,EXTREMO OESTE,4208401,SC,ITAPIRANGA
852362,2024-06-30,69754675872,IMBUIA,72,701405674588936,IMBUIA,2023-03-06,GF9670,FAIXA ETARIA,FAIXA ETARIA,...,qt_70_74,106.0,-27.498028,-49.413049,5982,VALE DO ITAJAI,ALTO VALE DO ITAJAÍ,4207403,SC,IMBUIA

In [239]:
nomes_sexo = {
'F' : 'Feminino',
'M' : 'Masculino',
'I' : 'Indefinido'
}

data['paciente_enum_sexo_biologico'] = data['paciente_enum_sexo_biologico'].replace(nomes_sexo)

In [240]:
########################### CONEXAO TABELA IMUNIZAÇÃO ###########################

conexao = pg.connect(database = "*****",
                           host="*****",
                           user="*****",
                           password="Tr@*****",
                           port="*****")


cursor = conexao.cursor()
query = "SELECT * FROM ibge.ibge_com_faixa_etaria_ano WHERE ano = '2022' and idade >= '12'"

cursor.execute(query)
resultados = cursor.fetchall()

data_faixa_etaria = pd.DataFrame(resultados, columns=[desc[0] for desc in cursor.description])

In [241]:
mapeamento_faixa_etaria = {
    'qt_0_4': '0-04 anos',
    'qt_5_9': '05-09 anos',
    'qt_10_11': '10-11 anos',
    'qt_12_14': '12-14 anos',
    'qt_15_17': '15-17 anos',
    'qt_18_19': '18-19 anos',
    'qt_20_24': '20-24 anos',
    'qt_25_29': '25-29 anos',
    'qt_30_34': '30-34 anos',
    'qt_35_39': '35-39 anos',
    'qt_40_44': '40-44 anos',
    'qt_45_49': '45-49 anos',
    'qt_50_54': '50-54 anos',
    'qt_55_59': '55-59 anos',
    'qt_60_64': '60-64 anos',
    'qt_65_69': '65-69 anos',
    'qt_70_74': '70-74 anos',
    'qt_75_79': '75-79 anos',
    'qt_80_ou_mais': '80 anos ou mais',
}

data_faixa_etaria['faixa_etaria'] = data_faixa_etaria['faixa_etaria'].replace(mapeamento_faixa_etaria)
data['faixa_etaria_2'] = data['faixa_etaria_2'].replace(mapeamento_faixa_etaria)

In [301]:
data_faixa_etaria['ano'] = data_faixa_etaria['ano'].astype(int)
data_faixa_etaria['pop'] = data_faixa_etaria['pop'].astype(int)
data_faixa_etaria['pop'].sum()
nomes_sexo = {'1' : 'Masculino','2' : 'Feminino'}
data_faixa_etaria['sexo'] = data_faixa_etaria['sexo'].replace(nomes_sexo)
data_faixa_etaria[data_faixa_etaria['cod_mun']=='420005']['pop'].sum()
data_faixa_etaria[data_faixa_etaria['cod_mun']=='420140']

        ano cod_mun       sexo idade  pop     faixa_etaria
19     2022  420140  Masculino    12  459       12-14 anos
360    2022  420140   Feminino    13  449       12-14 anos
1155   2022  420140  Masculino    16  491       15-17 anos
1450   2022  420140   Feminino    16  473       15-17 anos
1745   2022  420140  Masculino    17  522       15-17 anos
...     ...     ...        ...   ...  ...              ...
39181  2022  420140   Feminino    80  844  80 anos ou mais
39605  2022  420140  Masculino    28  541       25-29 anos
39764  2022  420140   Feminino    28  516       25-29 anos
40059  2022  420140  Masculino    29  552       25-29 anos
40354  2022  420140   Feminino    29  522       25-29 anos

[138 rows x 6 columns]

In [243]:
data.head(5)

,dat_carga,paciente_cpf,paciente_endereco_nm_municipio,paciente_idade,paciente_cns,estabelecimento_municipio_nome,vacina_data_aplicacao,vacina_lote,vacina_grupo_atendimento_nome,categoria,...,faixa_etaria_2,pop,nu_latitude,nu_longitude,total,macrorregiao_saude,regiao_saude,cod_ibge_7,uf,municipio
0,2024-06-30,15937330978,RIO DO OESTE,86,708602050709182,RIO DO OESTE,2023-03-06,GF9670,FAIXA ETARIA,FAIXA ETARIA,...,80 anos ou mais,153.0,-27.193396,-49.796999,7747,VALE DO ITAJAI,ALTO VALE DO ITAJAÍ,4214607,SC,RIO DO OESTE
1,2024-06-30,18207308915,NAVEGANTES,69,700505926316758,ITAJAI,2023-03-06,GF9670,PESSOAS DE 65 A 69 ANOS,FAIXA ETARIA,...,65-69 anos,1622.0,-26.899395,-48.655280,86401,FOZ DO RIO ITAJAI,FOZ DO RIO ITAJAÍ,4211306,SC,NAVEGANTES
2,2024-06-30,28001257053,PASSO DE TORRES,63,707000814406434,PASSO DE TORRES,2023-03-06,GJ5106,FAIXA ETARIA,FAIXA ETARIA,...,60-64 anos,400.0,-29.323230,-49.722518,12897,SUL,EXTREMO SUL CATARINENSE,4212254,SC,PASSO DE TORRES
3,2024-06-30,41984749900,JOINVILLE,61,708307221012560,JOINVILLE,2023-03-06,GF9670,PESSOAS DE 18 A 64 ANOS,FAIXA ETARIA,...,60-64 anos,15383.0,-26.305088,-48.846093,616317,NORTE E NORDESTE,NORDESTE,4209102,SC,JOINVILLE
4,2024-06-30,42019133920,JOINVILLE,75,705701442301030,JOINVILLE,2023-03-06,GF9670,PESSOAS DE 75 A 79 ANOS,FAIXA ETARIA,...,75-79 anos,5461.0,-26.305088,-48.846093,616317,NORTE E NORDESTE,NORDESTE,4209102,SC,JOINVILLE

In [311]:
casos_agrupados = data.groupby(['cod_ibge_6', 'regiao_saude','municipio', 'paciente_enum_sexo_biologico', 'faixa_etaria_2']).size().reset_index(name='contagem_dose')
casos_agrupados
casos_agrupados = casos_agrupados.rename(columns={
    'cod_ibge_6': 'cod_mun',
    'paciente_enum_sexo_biologico': 'sexo',
    'faixa_etaria_2':'faixa_etaria'
})

casos_agrupados
agrupado = data_faixa_etaria.groupby(['cod_mun', 'sexo', 'faixa_etaria'])['pop'].unique().apply(sum).reset_index()


agrupado['cod_mun'] = agrupado['cod_mun'].astype(int)
casos_agrupados['cod_mun'] = casos_agrupados['cod_mun'].astype(int)

In [312]:
merged_data_municipio = pd.merge(casos_agrupados, agrupado, on=['cod_mun', 'sexo', 'faixa_etaria'], how='left')
merged_data_municipio['porcentagem'] = round(merged_data_municipio['contagem_dose']/ merged_data_municipio['pop']*100,2)
merged_data_municipio



cobertura7 = merged_data_municipio.groupby(['municipio', 'sexo','faixa_etaria']).agg({'pop':'sum','contagem_dose':'sum'}).reset_index()
cobertura7['porcentagem'] = round(cobertura7['contagem_dose']/ cobertura7['pop']*100,2)
cobertura7.head(5)



cobertura8 = cobertura7.groupby(['faixa_etaria', 'sexo']).agg({'pop':'sum', 'contagem_dose':'sum'}).reset_index()
cobertura8['porcentagem'] = round(cobertura8['contagem_dose']/ cobertura8['pop']*100,2)
cobertura8['contagem_dose'].sum()
cobertura7['contagem_dose'].sum()
merged_data_municipio.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8813 entries, 0 to 8812
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cod_mun        8813 non-null   int32
 1   regiao_saude   8813 non-null   object
 2   municipio      8813 non-null   object
 3   sexo           8813 non-null   object
 4   faixa_etaria   8813 non-null   object
 5   contagem_dose  8813 non-null   int64
 6   pop            8812 non-null   float64
 7   porcentagem    8812 non-null   float64
dtypes: float64(2), int32(1), int64(1), object(4)
memory usage: 585.2+ KB

In [313]:
#merged_data_municipio.groupby(['municipio']).agg({'pop':'sum', 'contagem_dose':'sum'}).reset_index()

,cod_mun,regiao_saude,municipio,sexo,faixa_etaria,contagem_dose,pop,porcentagem
0,420005,MEIO OESTE,ABDON BATISTA,Feminino,12-14 anos,1,43.0,2.33
1,420005,MEIO OESTE,ABDON BATISTA,Feminino,15-17 anos,1,60.0,1.67
2,420005,MEIO OESTE,ABDON BATISTA,Feminino,18-19 anos,3,28.0,10.71
3,420005,MEIO OESTE,ABDON BATISTA,Feminino,20-24 anos,8,60.0,13.33
4,420005,MEIO OESTE,ABDON BATISTA,Feminino,25-29 anos,11,60.0,18.33
...,...,...,...,...,...,...,...,...
8808,422000,CARBONÍFERA,BALNEÁRIO RINCÃO,Masculino,60-64 anos,112,543.0,20.63
8809,422000,CARBONÍFERA,BALNEÁRIO RINCÃO,Masculino,65-69 anos,145,457.0,31.73
8810,422000,CARBONÍFERA,BALNEÁRIO RINCÃO,Masculino,70-74 anos,164,276.0,59.42
8811,422000,CARBONÍFERA,BALNEÁRIO RINCÃO,Masculino,75-79 anos,105,147.0,71.43
8812,422000,CARBONÍFERA,BALNEÁRIO RINCÃO,Masculino,80 anos ou mais,71,148.0,47.97

In [314]:

import psycopg2

conn = psycopg2.connect(
    database="*****",
    user="*****",
    password="*****",
    host="****",
    port="****"
)

try:
    cursor = conn.cursor()
    conn.autocommit = False
    
    # Truncate na tabela antes de inserir novos dados
    cursor.execute('TRUNCATE TABLE painel_python.tabela_bivalente_cobertura_municipios;')
    
    for index, row in merged_data_municipio.iterrows():
        cursor.execute(
            'INSERT INTO painel_python.tabela_bivalente_cobertura_municipios'
            '( "cod_mun", "regiao_saude", "municipio", "sexo", "faixa_etaria", "contagem_dose", "pop", "porcentagem") '
            'VALUES (%s, %s, %s, %s, %s, %s, %s, %s);',
            (
                row["cod_mun"],
                row["regiao_saude"],
                row["municipio"],
                row["sexo"],
                row['faixa_etaria'],
                row['contagem_dose'],
                row['pop'],
                row['porcentagem']

            )
        )
    conn.commit()
except Exception as e:
    conn.rollback()
    print("Erro:", e)
finally:
    cursor.close()
    conn.close()

REGIAO

In [248]:
# bivalente_regiao_populacao_total = data.groupby(['regiao_saude'])['pop'].unique().reset_index()
# bivalente_regiao_populacao_total

# bivalente_regiao_populacao_total = bivalente_regiao_populacao_total.groupby(['regiao_saude'])['pop'].sum().reset_index()


# bivalente_regiao_populacao_total = bivalente_regiao_populacao_total.rename(columns={
#     'regiao_saude':'regiao_saude'
    
#     })
# bivalente_regiao_populacao_total

POPULAÇÃO POR REGIAO

In [249]:
bivalente_regiao_populacao_total = data[['regiao_saude', 'total']].groupby(['regiao_saude', 'total']).nunique().reset_index()
bivalente_regiao_populacao_total = bivalente_regiao_populacao_total.groupby(['regiao_saude'])['total'].sum().reset_index()



bivalente_regiao_populacao_total

                 regiao_saude    total
0    ALTO URUGUAI CATARINENSE   154808
1         ALTO VALE DO ITAJAÍ   309808
2   ALTO VALE DO RIO DO PEIXE   287459
3                 CARBONÍFERA   446838
4               EXTREMO OESTE   241277
5     EXTREMO SUL CATARINENSE   222182
6           FOZ DO RIO ITAJAÍ   810890
7        GRANDE FLORIANÓPOLIS  1356861
8                      LAGUNA   381530
9                  MEIO OESTE   193657
10       MÉDIO VALE DO ITAJAÍ   812968
11                   NORDESTE   778481
12                      OESTE   408924
13             PLANALTO NORTE   370576
14          SERRA CATARINENSE   295210
15            VALE DO ITAPOCU   331693
16                    XANXERÊ   207199

MEDIDA POPULAÇÃO POR SEXO E FAIXA ETARIA

In [250]:
populacao_regional = merged_data_municipio.groupby(['regiao_saude', 'sexo', 'faixa_etaria'])['pop'].unique().apply(sum).reset_index()
populacao_regional

                 regiao_saude       sexo     faixa_etaria     pop
0    ALTO URUGUAI CATARINENSE   Feminino       12-14 anos  2085.0
1    ALTO URUGUAI CATARINENSE   Feminino       15-17 anos  2016.0
2    ALTO URUGUAI CATARINENSE   Feminino       18-19 anos  1664.0
3    ALTO URUGUAI CATARINENSE   Feminino       20-24 anos  5198.0
4    ALTO URUGUAI CATARINENSE   Feminino       25-29 anos  5493.0
..                        ...        ...              ...     ...
540                   XANXERÊ  Masculino       60-64 anos  4982.0
541                   XANXERÊ  Masculino       65-69 anos  3769.0
542                   XANXERÊ  Masculino       70-74 anos  2793.0
543                   XANXERÊ  Masculino       75-79 anos  1812.0
544                   XANXERÊ  Masculino  80 anos ou mais  1659.0

[545 rows x 4 columns]

MEDIDA TOTAL DE DOSES APLICADAS POR SEXO E FAIXA ETARIA

In [251]:
casos_agrupados_regiao = data.groupby(['regiao_saude', 'paciente_enum_sexo_biologico', 'faixa_etaria_2']).size().reset_index(name='contagem_dose')
casos_agrupados_regiao

casos_agrupados_regiao = casos_agrupados_regiao.rename(columns={
    'regiao_saude':'regiao_saude',
    'paciente_enum_sexo_biologico': 'sexo',
    'faixa_etaria_2':'faixa_etaria'
})

casos_agrupados_regiao

                 regiao_saude       sexo     faixa_etaria  contagem_dose
0    ALTO URUGUAI CATARINENSE   Feminino       12-14 anos             24
1    ALTO URUGUAI CATARINENSE   Feminino       15-17 anos             32
2    ALTO URUGUAI CATARINENSE   Feminino       18-19 anos            163
3    ALTO URUGUAI CATARINENSE   Feminino       20-24 anos            369
4    ALTO URUGUAI CATARINENSE   Feminino       25-29 anos            396
..                        ...        ...              ...            ...
540                   XANXERÊ  Masculino       60-64 anos           1216
541                   XANXERÊ  Masculino       65-69 anos           1218
542                   XANXERÊ  Masculino       70-74 anos           1167
543                   XANXERÊ  Masculino       75-79 anos            741
544                   XANXERÊ  Masculino  80 anos ou mais            691

[545 rows x 4 columns]

MERGE TABELAS (populacao_regional, casos_agrupados_regiao)

In [292]:
# Faça o merge usando as colunas 'cod_mun' e 'Sexo' como chaves
merged_data_regiao = pd.merge(populacao_regional, casos_agrupados_regiao, on=['regiao_saude', 'sexo', 'faixa_etaria'], how='inner')

merged_data_regiao['porcentagem'] = round(merged_data_regiao['contagem_dose']/ merged_data_regiao['pop']*100,2)

merged_data_regiao['pop'] = merged_data_regiao['pop'].fillna(0)
merged_data_regiao['pop'] = merged_data_regiao['pop'].astype(int)

cobertura = merged_data_regiao.groupby(['regiao_saude', 'sexo','faixa_etaria']).agg({'pop':'sum','contagem_dose':'sum'}).reset_index()
cobertura['porcentagem'] = round(cobertura['contagem_dose']/ cobertura['pop']*100,2)

merged_data_regiao['contagem_dose'].sum()

852363

In [293]:
cobertura = cobertura.groupby(['faixa_etaria', 'sexo']).agg({'pop':'sum', 'contagem_dose':'sum'}).reset_index()
cobertura['porcentagem'] = round(cobertura['contagem_dose']/ cobertura['pop']*100,2)
cobertura['contagem_dose'].sum()

852363

In [294]:
cobertura3 = merged_data_regiao.groupby(['regiao_saude', 'sexo']).agg({'pop':'sum', 'contagem_dose':'sum'}).reset_index()
cobertura3['porcentagem'] = round(cobertura3['contagem_dose']/ cobertura3['pop']*100,2)
cobertura3
cobertura3 = cobertura3[['regiao_saude','sexo' ,'porcentagem']]

In [295]:
merged_data_regiao.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 545 entries, 0 to 544
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   regiao_saude   545 non-null    object
 1   sexo           545 non-null    object
 2   faixa_etaria   545 non-null    object
 3   pop            545 non-null    int32
 4   contagem_dose  545 non-null    int64
 5   porcentagem    544 non-null    float64
dtypes: float64(1), int32(1), int64(1), object(3)
memory usage: 27.7+ KB

In [296]:

import psycopg2

conn = psycopg2.connect(
    database="*****",
    user="*****",
    password="*****",
    host="****",
    port="****"
)

try:
    cursor = conn.cursor()
    conn.autocommit = False
    
    # Truncate na tabela antes de inserir novos dados
    cursor.execute('TRUNCATE TABLE painel_python.tabela_bivalente_cobertura_doses_faixa_etaria_regiao;')
    
    for index, row in merged_data_regiao.iterrows():
        cursor.execute(
            'INSERT INTO painel_python.tabela_bivalente_cobertura_doses_faixa_etaria_regiao'
            '("regiao_saude", "faixa_etaria" ,"sexo", "pop", "contagem_dose", "porcentagem") '
            'VALUES (%s, %s, %s, %s, %s, %s);',
            (
                row["regiao_saude"],
                row["faixa_etaria"],
                row["sexo"],
                row["pop"],
                row['contagem_dose'],
                row['porcentagem']
            )
        )
    conn.commit()
except Exception as e:
    conn.rollback()
    print("Erro:", e)
finally:
    cursor.close()
    conn.close()

In [297]:
tooltip_regiao_contagemdoses = merged_data_regiao.groupby(['regiao_saude'])['contagem_dose'].sum().reset_index()
tooltip_regiao_contagemdoses

#variavel que contem a população por regiao
bivalente_regiao_populacao_total

tooltip_mapa_regiao = pd.merge(tooltip_regiao_contagemdoses, bivalente_regiao_populacao_total, on=['regiao_saude'], how='inner')
tooltip_mapa_regiao['porcentagem'] = round(tooltip_mapa_regiao['contagem_dose']/tooltip_mapa_regiao['total']*100,2)

In [263]:
bivalente_regiao_populacao_total

                 regiao_saude    total
0    ALTO URUGUAI CATARINENSE   154808
1         ALTO VALE DO ITAJAÍ   309808
2   ALTO VALE DO RIO DO PEIXE   287459
3                 CARBONÍFERA   446838
4               EXTREMO OESTE   241277
5     EXTREMO SUL CATARINENSE   222182
6           FOZ DO RIO ITAJAÍ   810890
7        GRANDE FLORIANÓPOLIS  1356861
8                      LAGUNA   381530
9                  MEIO OESTE   193657
10       MÉDIO VALE DO ITAJAÍ   812968
11                   NORDESTE   778481
12                      OESTE   408924
13             PLANALTO NORTE   370576
14          SERRA CATARINENSE   295210
15            VALE DO ITAPOCU   331693
16                    XANXERÊ   207199

In [298]:
import psycopg2

conn = psycopg2.connect(
    database="*****",
    user="*****",
    password="*****",
    host="****",
    port="****"
)

try:
    cursor = conn.cursor()
    conn.autocommit = False
    
    # Truncate na tabela antes de inserir novos dados
    cursor.execute('TRUNCATE TABLE painel_python.bivalente_regiao_populacao_total;')
    
    for index, row in bivalente_regiao_populacao_total.iterrows():
        cursor.execute(
            'INSERT INTO painel_python.bivalente_regiao_populacao_total'
            '("regiao_saude", "total") '
            'VALUES (%s, %s);',
            (
                row["regiao_saude"],
                row["total"]
            )
        )
    conn.commit()
except Exception as e:
    conn.rollback()
    print("Erro:", e)
finally:
    cursor.close()
    conn.close()

In [271]:
data

,dat_carga,paciente_cpf,paciente_endereco_nm_municipio,paciente_idade,paciente_cns,estabelecimento_municipio_nome,vacina_data_aplicacao,vacina_lote,vacina_grupo_atendimento_nome,categoria,...,faixa_etaria_2,pop,nu_latitude,nu_longitude,total,macrorregiao_saude,regiao_saude,cod_ibge_7,uf,municipio
0,2024-06-30,15937330978,RIO DO OESTE,86,708602050709182,RIO DO OESTE,2023-03-06,GF9670,FAIXA ETARIA,FAIXA ETARIA,...,80 anos ou mais,153.0,-27.193396,-49.796999,7747,VALE DO ITAJAI,ALTO VALE DO ITAJAÍ,4214607,SC,RIO DO OESTE
1,2024-06-30,18207308915,NAVEGANTES,69,700505926316758,ITAJAI,2023-03-06,GF9670,PESSOAS DE 65 A 69 ANOS,FAIXA ETARIA,...,65-69 anos,1622.0,-26.899395,-48.655280,86401,FOZ DO RIO ITAJAI,FOZ DO RIO ITAJAÍ,4211306,SC,NAVEGANTES
2,2024-06-30,28001257053,PASSO DE TORRES,63,707000814406434,PASSO DE TORRES,2023-03-06,GJ5106,FAIXA ETARIA,FAIXA ETARIA,...,60-64 anos,400.0,-29.323230,-49.722518,12897,SUL,EXTREMO SUL CATARINENSE,4212254,SC,PASSO DE TORRES
3,2024-06-30,41984749900,JOINVILLE,61,708307221012560,JOINVILLE,2023-03-06,GF9670,PESSOAS DE 18 A 64 ANOS,FAIXA ETARIA,...,60-64 anos,15383.0,-26.305088,-48.846093,616317,NORTE E NORDESTE,NORDESTE,4209102,SC,JOINVILLE
4,2024-06-30,42019133920,JOINVILLE,75,705701442301030,JOINVILLE,2023-03-06,GF9670,PESSOAS DE 75 A 79 ANOS,FAIXA ETARIA,...,75-79 anos,5461.0,-26.305088,-48.846093,616317,NORTE E NORDESTE,NORDESTE,4209102,SC,JOINVILLE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
852358,2024-06-30,90916719987,FLORIANOPOLIS,52,703107604179590,BIGUACU,2023-06-14,2F3006A,FAIXA ETARIA,FAIXA ETARIA,...,50-54 anos,17334.0,-27.596904,-48.549454,537211,GRANDE FLORIANOPOLIS,GRANDE FLORIANÓPOLIS,4205407,SC,FLORIANÓPOLIS
852359,2024-06-30,44975732904,BLUMENAU,61,700501512216151,BLUMENAU,2023-04-20,GF9670,FAIXA ETARIA,FAIXA ETARIA,...,60-64 anos,9703.0,-26.918752,-49.066025,361261,VALE DO ITAJAI,MÉDIO VALE DO ITAJAÍ,4202404,SC,BLUMENAU
852360,2024-06-30,56156413049,PALHOCA,54,700406979498348,PALHOCA,2023-06-29,GJ9239,FAIXA ETARIA,FAIXA ETARIA,...,50-54 anos,6331.0,-27.642670,-48.669511,222598,GRANDE FLORIANOPOLIS,GRANDE FLORIANÓPOLIS,4211900,SC,PALHOÇA
852361,2024-06-30,14601737087,ITAPIRANGA,85,700604487048167,ITAPIRANGA,2023-03-03,GJ5106,FAIXA ETARIA,FAIXA ETARIA,...,80 anos ou mais,227.0,-27.171014,-53.709862,16638,GRANDE OESTE,EXTREMO OESTE,4208401,SC,ITAPIRANGA
852362,2024-06-30,69754675872,IMBUIA,72,701405674588936,IMBUIA,2023-03-06,GF9670,FAIXA ETARIA,FAIXA ETARIA,...,70-74 anos,106.0,-27.498028,-49.413049,5982,VALE DO ITAJAI,ALTO VALE DO ITAJAÍ,4207403,SC,IMBUIA

In [299]:
municipio_populacao_total = data[['regiao_saude', 'total']].groupby(['regiao_saude', 'total']).nunique().reset_index()
municipio_populacao_total

                 regiao_saude  total
0    ALTO URUGUAI CATARINENSE   1689
1    ALTO URUGUAI CATARINENSE   1856
2    ALTO URUGUAI CATARINENSE   2992
3    ALTO URUGUAI CATARINENSE   3653
4    ALTO URUGUAI CATARINENSE   4378
..                        ...    ...
290                   XANXERÊ  11192
291                   XANXERÊ  17392
292                   XANXERÊ  24791
293                   XANXERÊ  31918
294                   XANXERÊ  51607

[295 rows x 2 columns]